import type { Metadata } from "next";
import { Geist, Geist_Mono , Poppins } from "next/font/google";
import { ConditionalFooter } from "@/components/layout/conditional-footer";
import { Header } from "@/components/layout/header";
import { Providers } from "@/app/providers";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const poppins = Poppins({
  variable: "--font-poppins",
  subsets: ["latin"],
  weight: ["400", "500", "600", "700"],
});

export const metadata: Metadata = {
  title: "Venuze",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: LayoutProps<"/">) {
  return (
    <html
      lang="en"
      className={` ${poppins.variable} h-full antialiased`}
    >
      <head>
        <link
          rel="preload"
          as="image"
          href="/images/hero/hero.svg"
          fetchPriority="high"
        />
        <link rel="preload" as="image" href="/images/logo.svg" />
        <link rel="preload" as="image" href="/images/Venuze-icon.svg" />
        <link
          rel="preload"
          as="image"
          href="/images/Venuze-Textcolor-Logo%202.svg"
        />
      </head>
      <body className="min-h-full flex flex-col">
        <Providers>
          <Header />
          <main className="flex-1">{children}</main>
          <ConditionalFooter />
        </Providers>
      </body>
    </html>
  );
}
